version: "3"

services:

  docker-compose:
    build:
      args:
        http_proxy: http://192.168.31.222:808
        https_proxy: http://192.168.31.222:808
      context: ./
      dockerfile: Dockerfile
    image: lianshufeng/docker-compose
    privileged: true